# Generated by Django 4.1.6 on 2023-02-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.BigIntegerField(),
        ),
    ]
