# Generated by Django 4.1.6 on 2023-03-03 15:35

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('django_main', '0003_rename_article_article_newsarticleslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
