# Generated by Django 4.1.6 on 2023-03-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_main', '0004_rename_author_article_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='newsarticleslist',
        ),
        migrations.DeleteModel(
            name='NewsArticlesList',
        ),
    ]
