# Generated by Django 4.1.6 on 2023-04-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_main', '0005_remove_article_newsarticleslist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='article',
            name='opinion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
