# Generated by Django 4.1.6 on 2023-05-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_main', '0009_article_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('date',)},
        ),
    ]
