# Generated by Django 4.1.6 on 2023-05-09 14:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_main', '0010_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default=False, max_length=255, verbose_name='profile_pic'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_img',
            field=cloudinary.models.CloudinaryField(default=False, max_length=255, verbose_name='title_img'),
        ),
    ]
