# Generated by Django 4.1.6 on 2023-05-26 14:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_main', '0012_delete_image_alter_article_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title_img_url',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sports', 'Sports'), ('Politics', 'Politics'), ('Business', 'Business'), ('Technology', 'Technology'), ('Environment', 'Environment'), ('Relgion', 'Religion'), ('Events', 'Events'), ('School', 'School')], default=None, max_length=20),
        ),
    ]
