# Generated by Django 4.1.6 on 2023-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_main', '0013_rename_title_img_url_article_img_alter_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.JSONField(),
        ),
    ]
