# Generated by Django 4.1.6 on 2023-06-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_main', '0014_alter_article_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
